spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/market
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: epfzja1234@gmail.com
    password: zehpnoaaalfvvedy
    properties:
      mail:
        smtp:
          auto: true
          timeout: 5000
          starttls.enable: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


app:
  host: testHost
  testname: testName
